version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*os.Root).Close
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Remove
        - os.RemoveAll
